- name: Install nginx ingress (bare metal, nodeport)
  shell: kubectl apply -f "kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.7.1/deploy/static/provider/baremetal/deploy.yaml"
