#disable swap as required by kubernetes
- name: Disable SWAP in fstab
  become: true
  replace:
    path: /etc/fstab
    regexp: '(\/swapfile.*)$'
    replace: '# \1'

- name: Turn swap off
  shell: swapoff -a

- name: create /etc/sysctl.d/k8s.conf
  shell: "cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF"

- name: reload sys config
  shell: sysctl --system
  become: yes

- name: update cache
  apt:
    update_cache: yes

- name: update the system
  apt:
    name: "*"
    state: latest
  async: 1800 # maximum runtime - 30 min

- name: install useful packages
  apt:
    pkg:
    - python3
    - apt-transport-https
    - curl
    - ca-certificates
    - software-properties-common
    - ntp
    - vim
    - less
    - nfs-common
    - cifs-utils
    - autofs
    - git
    - net-tools
  become: true

# set net config as required by kubernetes
- name: add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

# set time sync services (default configurations)
- name: install ntp
  become: yes
  apt:
    name: ntp
    state: present


- name: start ntpd service
  become: yes
  service:
    name: ntp
    state: restarted
    enabled: yes

- name: install chrony
  become: yes
  apt:
    name: chrony
    state: present

- name: start chronyd  service
  become: yes
  service:
    name: chronyd
    state: restarted
    enabled: yes

- name: sync time
  become: yes
  ignore_errors: yes
  command: chronyc sources

- name: Disable services if enabled
  shell: if systemctl is-enabled --quiet firewalld; then systemctl stop firewalld && systemctl disable firewalld && echo disable_ok ; fi
  register: output
  changed_when: "'disable_ok' in output.stdout"

- name: update sysctl
  command: sysctl --system

- name: Add an apt signing key for docker
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg

- name: Add an apt repo for K8s
  shell: add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Add an apt signing key for K8s
  shell: curl -fsSL  https://packages.cloud.google.com/apt/doc/apt-key.gpg|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/k8s.gpg

- name: Add an apt repo for K8s
  shell: add-apt-repository -y "deb http://apt.kubernetes.io/ kubernetes-xenial main"

- name: update the system
  apt:
    name: "*"
    state: latest
    update_cache: yes
  async: 1800 # maximum runtime - 30 min
