- name: Initialize the Kubernetes cluster using kubeadm
  become: true
  command: "kubeadm init --kubernetes-version {{ k8s.kube_version }} --apiserver-cert-extra-sans={{ all.public_ip }} --pod-network-cidr={{ all.cidr }} --apiserver-advertise-address='0.0.0.0'"


- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command