# - name: remove centos7 old version
#   become: yes
#   apt:
#     name:
#       - docker
#       - docker-client
#       - docker-client-latest
#       - docker-common
#       - docker-latest
#       - docker-latest-logrotate
#       - docker-logrotate
#       - docker-engine
#       - containerd
#     state: absent



- name: update the system
  apt:
    name: "*"
    state: latest
    update_cache: yes
  async: 1800 # maximum runtime - 30 min
  
- name: install dependencies
  become: yes
  apt:
    name:
      - gnupg2 
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg-agent 
      - software-properties-common
      - thin-provisioning-tools
      - lvm2
      - policycoreutils-python-utils
      - python3-pip
      - python3-docker
      - containerd.io
    state: present

- name: Disable services if enabled
  shell: containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1

- name: Disable services if enabled
  shell: sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

- name: start containerd service
  become: yes
  service:
    name: containerd
    state: restarted
    enabled: yes

- name: Copy yamls to server
  copy: src=files/containerd.conf dest=/etc/modules-load.d/containerd.conf

- name: modprobe overlay
  shell: modprobe overlay
- name: modprobe br_netfilter
  shell: modprobe br_netfilter